lessons:
  outputs:
    dev:
      dataset: tyler_dbt
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: cedar-shard-464020-d6
      threads: 60
      type: bigquery
  target: dev
